export const GET_BOOKS = 'GET_BOOKS';
export const GET_FAVORITES = 'GET_FAVORITES';
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';
export const SET_MESSAGE = 'SET_MESSAGE';
export const UNSET_MESSAGE = 'UNSET_MESSAGE';
export const LOADING_START = 'LOADING_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';